gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/core/Maths.o src/core/Maths.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/RobotArmBase.o src/robot/RobotArmBase.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/RobotPart.o src/robot/RobotPart.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/appearance/Light.o src/appearance/Light.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/geometry/GeometryShape.o src/geometry/GeometryShape.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/Robot.o src/robot/Robot.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/core/WindowControl.o src/core/WindowControl.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/CubicCage.o src/robot/CubicCage.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/RobotClaw.o src/robot/RobotClaw.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/RobotArea.o src/robot/RobotArea.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/geometry/SimpleCylinder.o src/geometry/SimpleCylinder.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/RobotFinger.o src/robot/RobotFinger.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/shape/Shape.o src/shape/Shape.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/RobotDimensions.o src/robot/RobotDimensions.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/core/Text.o src/core/Text.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/RobotArm.o src/robot/RobotArm.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/RobotHand.o src/robot/RobotHand.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/main.o src/main.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/appearance/Position.o src/appearance/Position.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/RobotBase.o src/robot/RobotBase.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/RobotWindow.o src/robot/RobotWindow.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/shape/ShapeGroup.o src/shape/ShapeGroup.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/core/Application.o src/core/Application.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/appearance/Color.o src/appearance/Color.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/robot/Propeller.o src/robot/Propeller.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/geometry/Ring.o src/geometry/Ring.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/geometry/Cylinder.o src/geometry/Cylinder.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/appearance/Stipple.o src/appearance/Stipple.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/geometry/Rectangle.o src/geometry/Rectangle.cpp
gcc -Isrc/include -O0 -g3 -Wall -c -fmessage-length=0 -std=c++0x -o src/geometry/Disk.o src/geometry/Disk.cpp
gcc -o opengl-robot src/shape/ShapeGroup.o src/shape/Shape.o src/robot/RobotWindow.o src/robot/RobotPart.o src/robot/RobotHand.o src/robot/RobotFinger.o src/robot/RobotDimensions.o src/robot/RobotClaw.o src/robot/RobotBase.o src/robot/RobotArmBase.o src/robot/RobotArm.o src/robot/RobotArea.o src/robot/Robot.o src/robot/Propeller.o src/robot/CubicCage.o src/main.o src/geometry/SimpleCylinder.o src/geometry/Ring.o src/geometry/Rectangle.o src/geometry/GeometryShape.o src/geometry/Disk.o src/geometry/Cylinder.o src/core/WindowControl.o src/core/Text.o src/core/Maths.o src/core/Application.o src/appearance/Stipple.o src/appearance/Position.o src/appearance/Light.o src/appearance/Color.o -lGL -lGLU -lglut
